### PR TITLE
feat: [AF-02] - 📝  Support EnvVars

### PR DESCRIPTION
**Pull request by afranzi**
This PR aims to support ExtraEnvVars so we can inherit the Lightdash Chart and using the EnvVars to provide existing secrets properly instead of using the current secrets approach which forces to put the secrets as plain text in Github.

We are expanding the values file as the following one:
```yaml
lightdash:
  image:
    tag: 0.32.4
  extraEnvVars:
    - name: LIGHTDASH_SECRET
      valueFrom:
        secretKeyRef:
          name: lightdash-secrets
          key: lightdash-secret
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: lightdash-secrets
          key: postgresql-password
```

### CODE REVIEW

**Comment by owlas** [comment]
Hey @afranzi thanks for this!! Should the `env: ` key be inside the conditional block?

**Comment by afranzi** [comment]
> Hey @afranzi thanks for this!! Should the `env: ` key be inside the conditional block?

Yeap, good catch. Code updated :)

**Comment by owlas** [comment]
Oh one more thing @afranzi - there is already an `env` key for the main `lightdash` container spec. Should this live under there? Is many `env` keys supported? I expect not

**Comment by owlas** [comment]
Here: https://github.com/lightdash/helm-charts/blob/e11a9564bafe7001c00857358a89c94566e09923/charts/lightdash/templates/deployment.yaml#L37

**Comment by owlas** [comment]
Closing as extra env vars are supported by passing them to the configmap:

```
# values.yaml
lightdash:
  configMap:
    MY_PARAM: wooo
```

**Pull request closed without merging**
