### PR TITLE
Adding PGSSLMODE env variable

### PR DESCRIPTION
**Pull request by BogdanAntoniu78**
Adding PGSSLMODE env variable to allow different ways of certificates handling  in case of external database usage.

### CODE REVIEW

**Comment by DavidSpek** [comment]
@owlas Could you maybe have a quick look at this? This is currently a blocker for us to have lightdash onboarded on [Plural](https://www.plural.sh/).

**Comment by owlas** [comment]
Hey @DavidSpek just taking a look!

**Comment by owlas** [comment]
@DavidSpek you should be able to do this by adding this to your `values.yaml` file:

```
configMap:
  PGSSLMODE: prefer
```

**Comment by DavidSpek** [comment]
@owlas While that would be possible I think it would be good to have this setting exposed along with the other database settings since that's likely where people would expect to find it.

I would also like to recommend adding the `PGSSLMODE` option to the lightdash docs, since it actually took me going into the code to find the package being used and the into the code of the `pg` npm package to find the setting and available options.
For reference, the options are: `disable`, `prefer`, `require`, `verify-ca`, `verify-full`, and `no-verify`.

**Pull request closed without merging**
